### ISSUE TITLE
Change "listAssignees" endpoint to "listAvailableAssignees"

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-github-source#14]
This method corresponds to an endpoint to that returns a list of all available assignees within a repo:
https://github.com/aries-data/aries-activity-github-source/blob/master/lib/index.js#L46

Given that we also want to be able to return a list of assignees to specific issues within a repo, this endpoint should be renamed for clarity.

**Comment by macmccann** [comment]
closed with d24615f58a793ca06929be1972f25489bcb69fba
