### ISSUE TITLE
User parameter being passed into Issue Events unnecessarily

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-github-source#27]
`user` doesn't look to be part of the request for Issue Events -- the necessary parameter in it's place is `owner` which is already being passed in.
https://github.com/aries-data/aries-activity-github-source/blob/master/lib/index.js#L112

https://developer.github.com/v3/issues/events/#list-events-for-a-repository

**Comment by ryw** [comment]
no more work on aries
