### ISSUE TITLE
User Parameter being passed into pull requests unnecessarily

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-github-source#28]
`user` doesn't look to be part of the request for Pull Requests -- the necessary parameter in it's place is `owner` which is already being passed in.
https://github.com/aries-data/aries-activity-github-source/blob/master/lib/index.js#L124

https://developer.github.com/v3/issues/events/#list-events-for-a-repository

**Comment by ryw** [comment]
no more work on aries
