### ISSUE TITLE
Clarify repo `all` functionality in README.md

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-github-source#4]
It's unclear right now what "all" is defined as. Is it all the repos that the user has access to?

**Comment by jlaneve** [comment]
The activity gets a list of all the user's repos according to https://developer.github.com/v3/repos/#list-your-repositories. From their docs: "This includes repositories owned by the authenticated user, repositories where the authenticated user is a collaborator, and repositories that the authenticated user has access to through an organization membership."

**Comment by benjamingregory** [comment]
Got it @jlaneve - I'll clarify in the docs.

**Comment by benjamingregory** [comment]
Closed with de1e54c
