### ISSUE TITLE
Break `all` functionality into `all_user` and `all_org` 

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-github-source#5]
**Current Behavior**
`all` currently accesses all the repos the user has access to. There is no current way to pull all events/comments/etc for all repos WITHIN a given org.

**Expected Behavior**
The user can easily pull events/comment/commits from both all repos they have access to and all repos that are part of a specific organization they are part of.

**So the following pulls every repo the user can access:**
```
config: {
....,
"repo":"all_user"
}
```

**And this pulls all repo the user can access within a certain org**
```
config: {
....,
"repo":"all_org",
"org":"astronomer"
}
```

**Comment by jlaneve** [comment]
Created PR #6 to close this issue.

**Comment by benjamingregory** [comment]
@jlaneve Had to make a quick change to get `listIssues` to work with pulling in the orgs instead of user. When the `allOrg` parameter was set, the requests would then be made as `{user}\{repo_name}` instead of `{org}\{repo_name}`. 

Take a look and refactor to have the `listIssues` accept a single repo as normal if `allOrg` is not present and update the other methods to work the same.

`allUser` also shouldn't assume that all the repos the user has access to is going to directly be listed under the user itself.

**Comment by benjamingregory** [comment]
@mac Can this be closed with your changes? If so, close with the commit reference.
