### ISSUE TITLE
listIssueComments missing number parameter

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-github-source#8]
It looks like the API requires an issue number to be passed in.
https://developer.github.com/v3/issues/comments/
https://github.com/aries-data/aries-activity-github-source/blob/master/lib/index.js#L52

**Comment by dansweet1** [comment]
Testing to ensure number parameter and test to verify was implemented correctly. Verifying with Mike in our weekly huddle that what I did was correct as well.

**Comment by dansweet1** [comment]
Noticed the CircleCI build failed. Investigating this so pull request can be approved and moving onto Google Sheets documentation and learning O-AUTH.

**Comment by dansweet1** [comment]
@benjamingregory as soon as the lintFix branch PR is approved I can pull down the changes into this branch and resubmit this PR.
